name: Actualização de Streams
on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v4

      - name: update streams
        run: cd M3U && sh streams.sh

      - name: update total channels
        run: |
          TOTAL=$(grep -c '^#EXTINF:-1' M3U/iptv_streams.m3u)
          DATETIME=$(date '+%Y-%m-%d %H:%M:%S')

          sed -i "s/^# (●) Total de Canais:.*/# (●) Total de Canais: $TOTAL/" M3U/iptv_streams.m3u
          sed -i "s/^# (●) Lista Actualizada a:.*/# (●) Lista Actualizada a: $DATETIME/" M3U/iptv_streams.m3u

      - name: setup git config
        run: |
          git config user.name "📺 "
          git config user.email "<>"

      - name: commit
        run: |
          git pull
          cd M3U && git add *.m3u
          git commit -m "Actualização de Streams"
          git push origin main
